name: nowapps
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  animate_do: ^2.1.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  get: ^4.6.5
  get_storage: ^2.0.3
  google_fonts: ^3.0.1
  page_transition: ^2.0.9
  pin_code_fields: ^7.4.0
  shimmer: ^2.0.0
  sizer: ^2.0.15
  sqflite: ^2.0.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true
  assets:
    - assets/
